[2025-01-16T01:12:59.464Z] info: docker.yaml was copied to the config folder
[2025-01-16T01:12:59.469Z] info: services.yaml was copied to the config folder
[2025-01-16T01:12:59.470Z] info: bookmarks.yaml was copied to the config folder
[2025-01-16T01:12:59.487Z] info: widgets.yaml was copied to the config folder
[2025-01-16T01:12:59.489Z] info: custom.css was copied to the config folder
[2025-01-16T01:12:59.491Z] info: custom.js was copied to the config folder
[2025-01-16T01:12:59.774Z] info: kubernetes.yaml was copied to the config folder
[2025-01-19T04:53:09.517Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:53:10.169Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:53:17.615Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:53:28.470Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:18.603Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:18.692Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:19.237Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:25.432Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:37.401Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:44.550Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:50.370Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:55:52.088Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:56:06.103Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:56:29.571Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:58:18.075Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:58:18.107Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:58:18.651Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:58:26.387Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:58:45.746Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:58:54.969Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:59:28.792Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:59:28.861Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:59:29.405Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:59:34.176Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T04:59:39.582Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T05:00:31.062Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T05:00:34.549Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-19T05:00:36.933Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:29:58.845Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:29:59.009Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:29:59.941Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:33:51.237Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:39:50.084Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:39:50.333Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:40:11.835Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:40:18.267Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:41:44.875Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:42:02.457Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T01:42:19.117Z] error: <service-helpers> Error getting services from Docker server 'my-docker': Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
[2025-01-22T02:43:35.683Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:38.181Z] error: <index> YAMLException: expected a single document in the stream, but found more
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2812:9)
    at bookmarksResponse (/app/.next/server/pages/index.js:3755:69)
    at async getStaticProps (/app/.next/server/pages/index.js:3262:23)
    at async Object.renderToHTML (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/render.js:386:20)
    at async doRender (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:687:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:796:28)
    at async /app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/response-cache/index.js:80:36
[2025-01-22T02:43:38.369Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:39.543Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:40.249Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:40.663Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:40.811Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:41.005Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:41.205Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:41.758Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:41.933Z] error: expected a single document in the stream, but found more
[2025-01-22T02:43:42.111Z] error: expected a single document in the stream, but found more
[2025-01-22T02:44:26.047Z] error: expected a single document in the stream, but found more
[2025-01-22T02:44:27.238Z] error: expected a single document in the stream, but found more
[2025-01-22T02:44:27.416Z] error: expected a single document in the stream, but found more
[2025-01-22T02:44:27.595Z] error: expected a single document in the stream, but found more
[2025-01-22T02:44:53.285Z] error: expected a single document in the stream, but found more
[2025-01-22T02:44:53.682Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:04.058Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:04.780Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:04.945Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:05.146Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:06.834Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:31.500Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:32.190Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:33.288Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:33.666Z] error: expected a single document in the stream, but found more
[2025-01-22T02:45:52.666Z] error: expected a single document in the stream, but found more
[2025-01-22T02:46:46.488Z] error: expected a single document in the stream, but found more
[2025-01-22T02:46:47.071Z] error: expected a single document in the stream, but found more
[2025-01-22T02:46:47.385Z] error: expected a single document in the stream, but found more
[2025-01-22T02:46:47.541Z] error: expected a single document in the stream, but found more
[2025-03-23T16:17:33.637Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:33.680Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:33.717Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.417Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.429Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.487Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.508Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.520Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.556Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.603Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-03-23T16:17:34.624Z] error: Host validation failed for: 192.168.86.11:3000. Hint: Set the HOMEPAGE_ALLOWED_HOSTS environment variable to allow requests from this host / port.
[2025-04-08T02:28:09.301Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:09.311Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:28:09.476Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:09.484Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:28:10.127Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:10.131Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:28:12.451Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.453Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.458Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.463Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.524Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.527Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.530Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.535Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.584Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.587Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.589Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.592Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.658Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.662Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.664Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.668Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.887Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.917Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.923Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.925Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.956Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.957Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:12.959Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:13.001Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:20.949Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:20.952Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:28:23.313Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.315Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.361Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.364Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.366Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.394Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.396Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.398Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.426Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.428Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.430Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.458Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.460Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.461Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.491Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.493Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.516Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.537Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.560Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.563Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.585Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.587Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.616Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:23.617Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:49.332Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:49.336Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:28:51.569Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.611Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.613Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.615Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.644Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.646Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.648Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.687Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.689Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.691Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.719Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.722Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.724Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.755Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.757Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.770Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.792Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.810Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.836Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.868Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.874Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.900Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.902Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.916Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:51.998Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:52.001Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:28:52.308Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:52.310Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:28:54.640Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.688Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.690Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.692Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.720Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.722Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.724Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.751Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.754Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.755Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.783Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.785Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.806Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.809Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.810Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.841Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.856Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.871Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.895Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.909Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.930Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.936Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.971Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:54.973Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:28:57.405Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:28:57.409Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:29:16.130Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:29:16.132Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:29:18.375Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.377Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.404Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.409Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.411Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.440Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.442Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.445Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.481Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.483Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.496Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.507Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.526Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.529Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.531Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.559Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.574Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.590Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.607Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.622Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.650Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.658Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.661Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:29:18.699Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:03.058Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:31:03.062Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:31:05.224Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.228Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.264Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.266Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.284Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.286Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.308Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.310Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.330Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.333Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.335Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.364Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.366Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.368Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.395Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.397Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.417Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.430Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.450Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.474Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.475Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.495Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.497Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:31:05.531Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:15.059Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:32:15.073Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:32:17.286Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.300Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.336Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.358Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.361Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.402Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.429Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.432Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.477Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.479Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.481Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.527Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.529Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.531Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.562Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.564Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.595Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.616Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.635Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.655Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.677Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.702Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.704Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:17.742Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:40.327Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T02:32:40.351Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T02:32:42.537Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.539Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.571Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.573Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.575Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.599Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.602Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.604Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.629Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.631Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.633Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.659Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.664Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.666Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.690Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.693Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.716Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.733Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.751Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.767Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.774Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.803Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.805Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T02:32:42.807Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:56.388Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T12:20:56.390Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T12:20:58.685Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:58.794Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:58.796Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:58.798Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:58.900Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:58.902Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:58.904Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:58.995Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.005Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.007Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.106Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.108Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.110Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.203Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.212Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.214Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.919Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.927Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:20:59.967Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:00.034Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:00.038Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:00.058Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:00.108Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:00.127Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.464Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.666Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.686Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.690Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.708Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.720Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.722Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.782Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.808Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.828Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.864Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.867Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.869Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.901Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.926Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:15.949Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:16.326Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T12:21:16.328Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T12:21:18.625Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:18.664Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:18.730Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:18.736Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:18.754Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:18.831Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:18.834Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:18.843Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:20.674Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T12:21:20.677Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T12:21:20.815Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:20.845Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:20.905Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:20.965Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:20.968Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:20.971Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:20.973Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.004Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.067Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.095Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.097Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.099Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.136Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.155Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.184Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:21.216Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.772Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.852Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.854Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.877Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.879Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.905Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.971Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:39.973Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.016Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.108Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.146Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.155Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.172Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T12:21:40.176Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T12:21:40.284Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.287Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.289Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:40.293Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.647Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.666Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.734Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.788Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.844Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.883Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.944Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:21:42.984Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.004Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.111Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.113Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.122Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.123Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.134Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.136Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.203Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.205Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.240Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.242Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.247Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.249Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.286Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.307Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.353Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:50.474Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T12:23:50.476Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T12:23:53.374Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T12:23:53.377Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T12:23:53.642Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.647Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.650Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.751Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.754Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.756Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.844Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.854Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:53.858Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:54.043Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:54.052Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:54.139Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:54.227Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:54.727Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:54.748Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:54.754Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:55.790Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:55.887Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:55.896Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:55.899Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:55.986Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:55.998Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:56.002Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T12:23:56.080Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:22.762Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T14:10:22.765Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T14:10:25.232Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.318Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.327Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.329Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.405Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.407Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.421Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.489Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.498Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.500Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.565Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.580Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.590Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.641Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.663Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:25.665Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.237Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.264Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.267Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.313Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.345Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.348Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.395Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:10:26.423Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.638Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.658Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T14:12:33.661Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T14:12:33.753Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.755Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.773Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.792Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.859Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.892Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.895Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.898Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.901Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:33.937Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:34.009Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:34.024Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:34.026Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:34.029Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:34.032Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.266Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.289Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.315Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.344Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.369Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.392Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.429Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:36.458Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:49.944Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T14:12:49.947Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T14:12:52.249Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.257Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.336Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.352Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.361Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.423Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.441Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.443Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.501Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.527Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.530Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.576Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.606Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.616Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.655Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:52.679Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.019Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.047Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.096Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.133Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.143Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.181Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.217Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:53.221Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.174Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.177Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.202Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.223Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.257Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.259Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.285Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.294Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.296Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.307Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.341Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.343Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.361Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.377Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.388Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.392Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:56.551Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T14:12:56.554Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T14:12:58.870Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:58.946Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:58.961Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:58.965Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:58.985Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:58.987Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:59.026Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:12:59.051Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.707Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.739Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.765Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.774Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.791Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.963Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.987Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:24.989Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.039Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.070Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.12:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.073Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.115Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.161Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.163Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.189Z] error: <dockerStatusService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:25.245Z] error: <dockerStatsService> Error: connect ECONNREFUSED 192.168.86.5:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.178Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.190Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.255Z] error: <service-helpers> Error getting services from Docker server 'my-docker-backup': Error: connect ECONNREFUSED 192.168.86.12:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.12:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.12',
  port: 2375
}
[2025-04-08T14:17:27.257Z] error: <service-helpers> Error getting services from Docker server 'my-docker-macmini': Error: connect ECONNREFUSED 192.168.86.5:2375
    at <unknown> (Error: connect ECONNREFUSED 192.168.86.5:2375) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.86.5',
  port: 2375
}
[2025-04-08T14:17:27.272Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.351Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.359Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.362Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.425Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-08T14:17:27.441Z] error: <dockerStatusService> Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at PipeConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:28.851Z] error: <dockerStatusService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:28.886Z] error: <dockerStatsService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:28.905Z] error: <dockerStatusService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:28.909Z] error: <dockerStatsService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:28.910Z] error: <dockerStatusService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:29.002Z] error: <dockerStatusService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:29.003Z] error: <dockerStatsService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:29.006Z] error: <dockerStatusService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:29.009Z] error: <dockerStatsService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:29.011Z] error: <dockerStatusService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-04-09T01:26:29.012Z] error: <dockerStatsService> Error: connect ECONNREFUSED 172.26.0.2:2375
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:01:52.854Z] error: <minecraftProxyHandler> Error: getaddrinfo EAI_AGAIN peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:01:53.415Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:01:53.419Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:02:28.616Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:02:29.199Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:02:29.391Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:02:57.038Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:02:57.043Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:03:06.016Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:03:06.058Z] error: <minecraftProxyHandler> Error: getaddrinfo ENOTFOUND peytonagher.duckdns.org
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:101:17)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:03:29.161Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 71.82.72.147:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:03:38.775Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:03:45.826Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:04:16.422Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:04:19.347Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:05:14.807Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:14:31.121Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:17:46.765Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:28:34.192Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:29:23.791Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:30:23.255Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:30:29.173Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:35:23.402Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:39:24.262Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:39:54.484Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-26T23:42:09.237Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:26:35.030Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:26:36.379Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:26:45.039Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:27:11.978Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:27:15.999Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:32:30.618Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:35:01.749Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:35:29.422Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:35:46.871Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:40:05.390Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:40:34.998Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:41:20.274Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:42:04.711Z] error: <minecraftProxyHandler> Error: connect ECONNREFUSED 192.168.86.5:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1636:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[2025-05-27T00:44:46.652Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:53:57.836Z] error: <httpProxy> Error calling http://192.168.86.10:32400/status/sessions...
[2025-05-31T16:53:57.854Z] error: undefined
[2025-05-31T16:53:57.851Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:32400
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:32400) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 32400
  }
]
[2025-05-31T16:53:57.852Z] error: <plexProxyHandler> HTTP 500 communicating with Plex. Data: [object Object]
[2025-05-31T16:53:57.859Z] error: TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at Function.from (node:buffer:325:9)
    at m (/app/.next/server/pages/api/services/proxy.js:45:10725)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:235:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:426:24)
[2025-05-31T16:53:57.889Z] error: <httpProxy> Error calling http://192.168.86.10:30047/api/v2...
[2025-05-31T16:53:57.891Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30047
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30047) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30047
  }
]
[2025-05-31T16:54:02.982Z] error: <httpProxy> Error calling http://192.168.86.10:32400/status/sessions...
[2025-05-31T16:54:02.987Z] error: undefined
[2025-05-31T16:54:02.986Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:32400
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:32400) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 32400
  }
]
[2025-05-31T16:54:02.986Z] error: <plexProxyHandler> HTTP 500 communicating with Plex. Data: [object Object]
[2025-05-31T16:54:02.994Z] error: TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at Function.from (node:buffer:325:9)
    at m (/app/.next/server/pages/api/services/proxy.js:45:10725)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:235:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:426:24)
[2025-05-31T16:54:03.876Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:54:05.289Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:56:03.270Z] error: <httpProxy> Error calling http://192.168.86.10/api/v2.0/alert/list...
[2025-05-31T16:56:03.271Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:80
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:80) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 80
  }
]
[2025-05-31T16:56:03.272Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.86.10/api/v2.0/alert/list
[2025-05-31T16:56:03.278Z] error: <httpProxy> Error calling http://192.168.86.10/api/v2.0/system/info...
[2025-05-31T16:56:03.278Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:80
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:80) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 80
  }
]
[2025-05-31T16:56:03.279Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T16:56:03.286Z] error: <httpProxy> Error calling http://192.168.86.10/api/v2.0/pool...
[2025-05-31T16:56:03.287Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:80
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:80) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 80
  }
]
[2025-05-31T16:56:03.287Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T16:56:03.311Z] error: <httpProxy> Error calling http://192.168.86.10/api/v2.0/pool/dataset...
[2025-05-31T16:56:03.312Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:80
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:80) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 80
  }
]
[2025-05-31T16:56:03.312Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.86.10/api/v2.0/pool/dataset
[2025-05-31T16:56:03.316Z] error: undefined
[2025-05-31T16:56:03.315Z] error: <httpProxy> Error calling http://192.168.86.10:32400/status/sessions...
[2025-05-31T16:56:03.315Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:32400
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:32400) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 32400
  }
]
[2025-05-31T16:56:03.316Z] error: <plexProxyHandler> HTTP 500 communicating with Plex. Data: [object Object]
[2025-05-31T16:56:03.318Z] error: <httpProxy> Error calling http://192.168.86.10:30047/api/v2...
[2025-05-31T16:56:03.320Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30047
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30047) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30047
  }
]
[2025-05-31T16:56:03.317Z] error: TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at Function.from (node:buffer:325:9)
    at m (/app/.next/server/pages/api/services/proxy.js:45:10725)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:235:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:426:24)
[2025-05-31T16:57:32.618Z] error: <httpProxy> Error calling http://192.168.86.10:30047/api/v2...
[2025-05-31T16:57:32.627Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30047
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30047) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30047
  }
]
[2025-05-31T16:57:34.922Z] error: <httpProxy> Error calling http://192.168.86.10:30047/api/v2...
[2025-05-31T16:57:34.931Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30047
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30047) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30047
  }
]
[2025-05-31T16:57:39.838Z] error: <httpProxy> Error calling http://192.168.86.10:32400/status/sessions...
[2025-05-31T16:57:39.842Z] error: undefined
[2025-05-31T16:57:39.839Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:32400
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:32400) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 32400
  }
]
[2025-05-31T16:57:39.841Z] error: <plexProxyHandler> HTTP 500 communicating with Plex. Data: [object Object]
[2025-05-31T16:57:39.849Z] error: TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at Function.from (node:buffer:325:9)
    at m (/app/.next/server/pages/api/services/proxy.js:45:10725)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async X (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:18441)
    at async z.render (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:19237)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:664:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:301:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:895:17)
    at async invokeRender (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:235:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:426:24)
[2025-05-31T16:57:39.971Z] error: <httpProxy> Error calling http://192.168.86.10:30047/api/v2...
[2025-05-31T16:57:39.978Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30047
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30047) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30047
  }
]
[2025-05-31T16:57:44.868Z] error: <httpProxy> Error calling http://192.168.86.10:30061/api/stats...
[2025-05-31T16:57:44.869Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30061
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30061) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30061
  }
]
[2025-05-31T16:57:45.052Z] error: <httpProxy> Error calling http://192.168.86.10:30047/api/v2...
[2025-05-31T16:57:45.056Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30047
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30047) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30047
  }
]
[2025-05-31T16:57:54.090Z] error: <httpProxy> Error calling http://192.168.86.10:30047/api/v2...
[2025-05-31T16:57:54.093Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 192.168.86.10:30047
      at <unknown> (Error: connect ECONNREFUSED 192.168.86.10:30047) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.86.10',
    port: 30047
  }
]
[2025-05-31T16:59:12.138Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool/dataset
[2025-05-31T16:59:12.142Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/alert/list
[2025-05-31T16:59:12.145Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T16:59:17.044Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool/dataset
[2025-05-31T16:59:17.048Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/alert/list
[2025-05-31T16:59:20.217Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T16:59:20.221Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T16:59:20.548Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:22.189Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:22.195Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:25.942Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:25.945Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:26.961Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:30.131Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:30.135Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:30.139Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T16:59:30.290Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T17:06:41.725Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T17:06:41.726Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T17:13:12.790Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T17:13:12.791Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T17:14:31.283Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/alert/list
[2025-05-31T17:14:31.284Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T17:14:40.043Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T17:14:58.176Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T17:14:58.177Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T17:14:58.179Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool/dataset
[2025-05-31T17:15:07.093Z] error: <minecraftProxyHandler> Error: Timed out.
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraftstatuspinger@1.2.2/node_modules/minecraftstatuspinger/dist/cjs/index.js:96:20)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
[2025-05-31T17:16:42.050Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/alert/list
[2025-05-31T17:16:42.053Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T20:56:57.053Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool
[2025-05-31T21:07:32.482Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool/dataset
[2025-05-31T21:07:32.484Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T21:15:03.046Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool/dataset
[2025-05-31T23:36:36.663Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/system/info
[2025-05-31T23:36:36.665Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool/dataset
[2025-05-31T23:36:47.046Z] error: <credentialedProxyHandler> HTTP Error 401 calling http://192.168.86.10/api/v2.0/pool/dataset
